name: pushover-actions

on:
  issues:
    types: [opened, edited]

jobs:
  pushover-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{secrets.PUSHOVER_APP_KEY}}
          PUSHOVER_USER: ${{secrets.PUSHOVER_USER_KEY}}
        with:
          status: ${{job.status}}
          title: CI Event - ${{github.repository}}
          message: ${{github.ref}}
          url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          url_title: "Open Pipeline"
          priority: "1"
